from celery import Celery
from celery.schedules import crontab
from flask import render_template_string
from flask_mail import Mail, Message
from datetime import datetime, timedelta
import csv, io, os

def make_celery(app):
    celery = Celery(app.import_name,
                    broker=app.config['CELERY_BROKER_URL'],
                    backend=app.config['CELERY_RESULT_BACKEND'])
    celery.conf.update(app.config)

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery

# Import app here (circular-safe)
from app import app
celery = make_celery(app)
mail = Mail(app)

# ── Celery Beat Schedule ──────────────────────────────────────────────────────
celery.conf.beat_schedule = {
    'daily-reminder-every-morning': {
        'task': 'tasks.send_daily_reminders',
        'schedule': crontab(hour=8, minute=0),  # 8 AM daily
    },
    'monthly-doctor-report': {
        'task': 'tasks.send_monthly_reports',
        'schedule': crontab(hour=7, minute=0, day_of_month=1),  # 1st of each month
    },
}
celery.conf.timezone = 'UTC'


# ── Task 1: Daily Reminders ───────────────────────────────────────────────────
@celery.task(name='tasks.send_daily_reminders')
def send_daily_reminders():
    from models import Appointment, Patient, User
    from app import db
    today = str(datetime.utcnow().date())
    appts = Appointment.query.filter_by(date=today, status='Booked').all()
    sent = 0
    for appt in appts:
        patient_user = appt.patient.user
        if patient_user.email:
            try:
                msg = Message(
                    subject='HMS – Appointment Reminder',
                    recipients=[patient_user.email],
                    body=(
                        f"Dear {patient_user.username},\n\n"
                        f"This is a reminder that you have an appointment today at {appt.time} "
                        f"with Dr. {appt.doctor.user.username} ({appt.doctor.specialization}).\n\n"
                        f"Please visit the hospital on time.\n\nRegards,\nHMS Team"
                    )
                )
                mail.send(msg)
                sent += 1
            except Exception as e:
                print(f"Failed to send reminder to {patient_user.email}: {e}")
    return f"Reminders sent: {sent}"


# ── Task 2: Monthly Doctor Report ─────────────────────────────────────────────
@celery.task(name='tasks.send_monthly_reports')
def send_monthly_reports():
    from models import Doctor, Appointment, Treatment
    from app import db
    now = datetime.utcnow()
    last_month = now.month - 1 if now.month > 1 else 12
    year = now.year if now.month > 1 else now.year - 1
    month_str = f"{year}-{str(last_month).zfill(2)}"

    doctors = Doctor.query.all()
    sent = 0
    for doc in doctors:
        doc_user = doc.user
        if not doc_user.email:
            continue
        appts = Appointment.query.filter(
            Appointment.doctor_id == doc.id,
            Appointment.date.like(f'{month_str}%'),
            Appointment.status == 'Completed'
        ).all()

        html_report = f"""
        <html><body>
        <h2>Monthly Activity Report – {month_str}</h2>
        <p>Doctor: <strong>Dr. {doc_user.username}</strong> | Specialization: {doc.specialization}</p>
        <p>Total Completed Appointments: <strong>{len(appts)}</strong></p>
        <table border='1' cellpadding='6' cellspacing='0' style='border-collapse:collapse;width:100%'>
          <tr style='background:#0d6efd;color:white'>
            <th>Date</th><th>Patient</th><th>Diagnosis</th><th>Prescription</th><th>Notes</th>
          </tr>
          {''.join(f"<tr><td>{a.date}</td><td>{a.patient.user.username}</td><td>{a.treatment.diagnosis if a.treatment else ''}</td><td>{a.treatment.prescription if a.treatment else ''}</td><td>{a.treatment.notes if a.treatment else ''}</td></tr>" for a in appts)}
        </table>
        <p style='margin-top:20px'>Generated by HMS on {now.strftime('%Y-%m-%d')}</p>
        </body></html>
        """
        try:
            msg = Message(
                subject=f'HMS Monthly Report – {month_str}',
                recipients=[doc_user.email],
                html=html_report
            )
            mail.send(msg)
            sent += 1
        except Exception as e:
            print(f"Failed to send report to {doc_user.email}: {e}")
    return f"Monthly reports sent: {sent}"


# ── Task 3: CSV Export (Patient-Triggered) ────────────────────────────────────
@celery.task(name='tasks.export_csv_task')
def export_csv_task(user_id):
    from models import Patient, Appointment, User
    from app import db
    patient = Patient.query.filter_by(user_id=user_id).first()
    if not patient:
        return 'Patient not found'

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(['Visit No', 'Patient', 'Doctor', 'Specialization',
                     'Date', 'Time', 'Status', 'Diagnosis', 'Prescription',
                     'Notes', 'Next Visit'])

    appts = Appointment.query.filter_by(patient_id=patient.id).order_by(Appointment.date).all()
    for i, a in enumerate(appts, 1):
        writer.writerow([
            i,
            patient.user.username,
            a.doctor.user.username,
            a.doctor.specialization,
            a.date,
            a.time,
            a.status,
            a.treatment.diagnosis if a.treatment else '',
            a.treatment.prescription if a.treatment else '',
            a.treatment.notes if a.treatment else '',
            a.treatment.next_visit if a.treatment else ''
        ])

    csv_content = output.getvalue()
    patient_email = patient.user.email

    if patient_email:
        try:
            msg = Message(
                subject='HMS – Your Treatment History CSV Export',
                recipients=[patient_email],
                body='Please find your treatment history attached.',
                attachments=[('treatment_history.csv', 'text/csv', csv_content.encode('utf-8'))]
            )
            mail.send(msg)
        except Exception as e:
            print(f"CSV email failed: {e}")

    return f"CSV export complete for user_id={user_id}"
